---
## 
- name: docker pre install
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present

- name: add key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes

- name:
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
